'use client'
import './../globals.css'
import NavBar from './../../components/navbar/index';

export const metadata = {
  title: 'Arte do Disfarce',
  description: 'Generated by create next app',
}

export default function ClientLayout({children}) {

  return (
      <>
        <NavBar></NavBar>
        {children}
      </>    
  )
  }