import './globals.css'
import AuthProvider from './context/AuthContext';

export const metadata = {
  title: 'Arte do Disfarce',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {

  return (
    <html lang="pt">
      <body /*className={inter.className}*/>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>     
        
  )
}
