import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './../components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Arte do Disfarce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
