import './globals.css'
import Provider from './providers/sessionProvider'

export const metadata = {
  title: 'Arte do Disfarce',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {

  return (
    <html lang="pt">
    <link rel="icon" type="image/x-icon" href="/images/artedodisfarcelogo.jpg"></link>
      <Provider>
        <body>
          {children}
        </body>
      </Provider>
    </html>
    
  )
}
