import './../globals.css'
import AuthProvider from './../context/AuthContext';
import Dashboard from './../../components/dashboard/index';

export const metadata = {
  title: 'Arte do Disfarce',
  description: 'Generated by create next app',
}

export default function AdmLayout({children}) {

  return (

    <html>
      <head></head>
      <body className="h-full bg-gray-100">
        <AuthProvider>
          <main>
            <Dashboard>
              {children}
            </Dashboard>
          </main>
        </AuthProvider>
      </body>
    </html>           
  )
}